language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - lerna bootstrap
script:
  - yarn build
notifications:
  email:
    on_success: change
    on_failure: always
